### PR TITLE
Show color during CI build

### PR DESCRIPTION
**Pull request by basil**
I realize this is purely subjective/superficial, but I think this would be a welcome change for those looking at CI build failures.

### CODE REVIEW

**Review by timja — APPROVED** [review]
sure 🤷

**Comment by basil** [comment]
Tested in jenkinsci/jenkins#6045

**Review by jglick — APPROVED** [review]
Great if it works.

**Comment by basil** [comment]
Back in draft state since apparently [`ansicolor` is broken](https://github.com/jenkinsci/jenkins/pull/6045#issuecomment-991219860).

**Comment by dduportal** [comment]
Hello @basil , do you feel that we should update and try again this PR?

Your initial request feels legit (and useful) but I'm not sure how to evaluate if ansicolor is still broken without disturbing contributors.

**Comment by basil** [comment]
The `ansicolor` plugin is not being actively developed and unfortunately I do not believe the regression has been fixed.

**Comment by dduportal** [comment]
> The `ansicolor` plugin is not being actively developed and unfortunately I do not believe the regression has been fixed.

Many thanks for the feedback

**Pull request closed without merging**
