### PR TITLE
Use ACI agents for Linux based builds.

### PR DESCRIPTION
**Pull request by slide**
This will use ACI (Azure Container Instances) agents instead of VM's. The default is to use ACI agents, with the ability to override in the plugin configuration.

CC @rtyler, @jglick, @daniel-beck

### CODE REVIEW

**Comment by rtyler** [comment]
This looks reasonable to me, I could have sworn I saw a similar change from @jglick somewhere already but now cannot find it.

Would it perhaps make sense to swap the default to _not_ use ACI, and then test against a few plugin repos?

Or would you rather #yolo and see what happens? :smile_cat:

**Comment by slide** [comment]
I was planning on #yolo :-)

**Comment by slide** [comment]
I believe @jglick's changes were to the Jenkinsfile for jenkinsci/jenkins

**Comment by slide** [comment]
If everyone would rather play it safe, I can switch the default.

**Comment by oleg-nenashev** [comment]
Our infrastructure breaks every week anyway, so I do not mid YOLO if it is
documented

**Comment by jglick** [comment]
Switching the default would break a bunch of builds in my experience:

* no `docker` CLI
* tests run as `root`

So let us make it opt-in.

**Comment by jglick** [comment]
[INFRA-2165](https://issues.jenkins-ci.org/browse/INFRA-2165) FTR

**Pull request merged**
