### PR TITLE
Add step to push test results to Codecov

### PR DESCRIPTION
**Pull request by stellargo**
CC @oleg-nenashev

### CODE REVIEW

**Comment by stellargo** [comment]
If this change is not needed here, I am happy to remove it. If it looks good, Ill file a JIRA and document it

**Comment by oleg-nenashev** [comment]
I may have misunderstood the discussion in Jira, but IIRc the intent was to publsh JaCoCo coverage reports. We can indeed deploy it to a service, but we could also publish the reports in Jenkins directly. have you considered using https://plugins.jenkins.io/jacoco/ for publishing reports right inside Jenkins?

**Comment by oleg-nenashev** [comment]
Or maybe even https://plugins.jenkins.io/code-coverage-api/

**Comment by stellargo** [comment]
Ok I will use Jacoco plugin. I just wanted those PR checks, but no issues this works too. Thanks :) Ill close the PR.

**Pull request closed without merging**
