### PR TITLE
Replace deprecated code coverage step with new step of coverage plugin

### LINKED ISSUE #644: Usage of deprecated `publishCoverage` step in `buildPlugin()`
According to the [pipeline docs](https://www.jenkins.io/doc/pipeline/steps/code-coverage-api/#publishcoverage-publish-coverage-report-deprecated), `publishCoverage` is deprecated. 
Yet, this is still called within [`buildPlugin()`](https://github.com/jenkins-infra/pipeline-library/blob/d6e19b741e7ea049c4e6761763f125e24945b06c/vars/buildPlugin.groovy#L149).

Code coverage should likely be published via `recordCoverage` calling the jacoco task.

### PR DESCRIPTION
**Pull request by uhafner**
Replace deprecated code coverage step with new step of coverage plugin to record the JaCoCo coverage results. Since the new recorder also understands PIT, a new option has been added to enable the recording of mutation test results. Both recording steps can be configured by developers using a configuration map.

This PR will fix #644.

Example projects that use the new `buildPlugin` script already:
- https://github.com/jenkinsci/code-coverage-api-plugin
- https://github.com/jenkinsci/forensics-api-plugin
- https://github.com/jenkinsci/analysis-model
- https://github.com/jenkinsci/coverage-model

When this change is active the following new features are supported:

* Coverage analysis of projects and pull requests: The plugin now computes and shows the absolute coverage of the project, the coverage of the modified files and the coverage of the modified lines, so you can see how the changes actually affect the code coverage. Additionally, the delta of these coverages with respect to the reference build are computed and the coverage changes created by changed test cases (indirect coverage changes).

summary

* Quality Gates: You can specify an arbitrary number of quality gates that allow to set the build to unstable or failed if the thresholds are not met. For each quality gate the metric (branch coverage, complexity, etc.) and the baseline (whole project, changed files, etc.) can be defined.

quality-gates
quality-gates-result

* Cyclomatic Complexity and LOC metrics: Several coverage parsers support the measurement of cyclomatic complexity and lines of code. These metrics are now computed and recorded as well:

all-metrics

* GitHub checks report to show the detailed line and branch coverage results for pull request:

jacoco-coverage-checks
jacoco-coverage-checks-annotations

* GitHub checks report to show the detailed line and mutation coverage results for pull request:

pit-coverage-checks
pit-coverage-checks-annotations

### CODE REVIEW

**Review by timja — DISMISSED** [review]

**Comment by jglick** [comment]
Neat, I had not heard of PIT before. Not mentioned in `plugin-pom` so I guess the current users have configured it specially?

**Comment by uhafner** [comment]
> Not mentioned in plugin-pom so I guess the current users have configured it specially?

I can add a corresponding profile to the parent pom if there is interest. 
- [Configuration](https://github.com/jenkinsci/analysis-pom-plugin/blob/1da533aa87564baeb1f5f337ebd475cb2896df8a/pom.xml#L311-L339)
- [Profile](https://github.com/jenkinsci/analysis-pom-plugin/blob/1da533aa87564baeb1f5f337ebd475cb2896df8a/pom.xml#L650-L668)

**Comment by MarkEWaite** [comment]
I have PIT configured on one of the plugins that I maintain ([platformlabeler instructions](https://github.com/jenkinsci/platformlabeler-plugin/blob/master/CONTRIBUTING.md#mutation-testing)).  I only run the PIT tests when I'm actively trying to improve the effectiveness of the tests on that plugin.

**Review by basil — COMMENTED** [review]
> You need to enable it by setting the property `skip` to `true` as well.

Shouldn't this read "[…] by setting the property `skip` to `false` […]"?

**Review by NotMyFault — DISMISSED** [review]
Thanks!

**Comment by uhafner** [comment]
> > You need to enable it by setting the property `skip` to `true` as well.
> 
> Shouldn't this read "[…] by setting the property `skip` to `false` […]"?

Yes, you are right. Fixed it right now.

**Review by basil — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]

**Comment by uhafner** [comment]
> > Not mentioned in plugin-pom so I guess the current users have configured it specially?
> 
> I can add a corresponding profile to the parent pom if there is interest.
> 
> * [Configuration](https://github.com/jenkinsci/analysis-pom-plugin/blob/1da533aa87564baeb1f5f337ebd475cb2896df8a/pom.xml#L311-L339)
> * [Profile](https://github.com/jenkinsci/analysis-pom-plugin/blob/1da533aa87564baeb1f5f337ebd475cb2896df8a/pom.xml#L650-L668)

After thinking about that a little bit longer: I think that such a change requires more effort. In my plugins I have a clean separation of integration tests (based on the Jenkins rule) and unit tests. When running PIT I am using only unit tests to improve the test quality, otherwise the evaluation of the mutation results with the test suite would be too slow.

**Pull request merged**
