### PR TITLE
Deprecate recommendedConfigurations

### PR DESCRIPTION
**Pull request by jglick**
Amends #92 (which broke some builds) and supersedes #94. Better to specify configurations you want in your `Jenkinsfile`, and adjust those in PRs.

### CODE REVIEW

**Comment by jglick** [comment]
See discussion in https://github.com/jenkins-infra/pipeline-library/pull/94#issuecomment-522657761 and elsewhere.

**Review by olblak — DISMISSED** [review]

**Comment by jglick** [comment]
Updated to subsume #146.

**Review by oleg-nenashev — DISMISSED** [review]
I disagree with removing it. The whole reason of `buildPlugin.recommendedConfigurations()` was to remove the need to manually manage versions for plugin developers. Definitely the suggested approach did not get well accepted once the version was updated, but the behavior is documented explicitly.

We need better reporting to ensure that the Pipeline acts as an advisory tool without failing the build for recent versions, but IMO the feature itself makes sense and should be retained

**Comment by jglick** [comment]
> The whole reason of `buildPlugin.recommendedConfigurations()` was to remove the need to manually manage versions for plugin developers.

Yes; and I am saying this experiment failed. By contrast, Dependabot on `pom.xml` is (by and large) working. We could try to find a way to make Dependabot offer `jenkins.version` bumps, if we wanted to guide plugins to just build against one recent LTS version (critical bug fixes could be backported on demand).

> better reporting to ensure that the Pipeline acts as an advisory tool without failing the build for recent versions

I do not see how that could work. Either the build passes or it fails; developers need to be able to tell whether their changes are broken or not. If you want to run PCT on `master` of a few dozen popular plugins in another job and have someone trawling through failures, fine, but that would not be part of `*-plugin/Jenkinsfile` (that is actually pretty close to what `bom` builds are doing).

**Comment by jglick** [comment]
Continues to be a problem in various plugins, and people who know continue to remove it.

**Review by timja — APPROVED** [review]

**Review by basil — APPROVED** [review]
+`UINT64_MAX`

**Pull request merged**
